/**
 * stamp.mjs — cache-busting for GitHub Pages (which serves everything with
 * max-age=600). Without it a phone can keep an old main.js while fetching a
 * new config.js, and the two halves of the app disagree.
 *
 * Gives every module and the stylesheet a ?v=<content hash> via an import map
 * in index.html, so a changed file always gets a new URL and unchanged files
 * stay cached. Run before committing (the pre-commit hook does it for you):
 *
 *   node scripts/stamp.mjs
 */

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const hash = (file) => createHash('sha1').update(readFileSync(join(root, file))).digest('hex').slice(0, 8);

const modules = readdirSync(join(root, 'src'))
  .filter((f) => f.endsWith('.js'))
  .sort()
  .map((f) => `src/${f}`);
const v = Object.fromEntries([...modules, 'styles/main.css'].map((f) => [f, hash(f)]));

const map = { imports: Object.fromEntries(modules.map((f) => [`./${f}`, `./${f}?v=${v[f]}`])) };
const block = `<!-- importmap:start (generated by scripts/stamp.mjs) -->
  <script type="importmap">
${JSON.stringify(map, null, 2).replace(/^/gm, '  ')}
  </script>
  <!-- importmap:end -->`;

const indexPath = join(root, 'index.html');
let html = readFileSync(indexPath, 'utf8');

if (html.includes('<!-- importmap:start')) {
  html = html.replace(/<!-- importmap:start[\s\S]*?<!-- importmap:end -->/, block);
} else {
  // The import map must come before any module script or modulepreload.
  html = html.replace(/(\s*)<link rel="modulepreload"/, `$1${block}$1<link rel="modulepreload"`);
}
html = html
  .replace(/href="styles\/main\.css(\?v=[0-9a-f]+)?"/, `href="styles/main.css?v=${v['styles/main.css']}"`)
  .replace(/href="src\/main\.js(\?v=[0-9a-f]+)?"/, `href="src/main.js?v=${v['src/main.js']}"`)
  .replace(/src="src\/main\.js(\?v=[0-9a-f]+)?"/, `src="src/main.js?v=${v['src/main.js']}"`);

writeFileSync(indexPath, html);
console.log('stamped', Object.entries(v).map(([f, h]) => `${f}@${h}`).join(' '));
